name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install pytest fastapi[all] sqlmodel passlib
      - name: Run backend tests
        run: PYTHONPATH=main pytest -q --disable-warnings

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main/frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - run: npm test -- --watchAll=false
