name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install everything from your root requirements.txt
          python -m pip install -r requirements.txt

      - name: Show installed packages
        run: python -m pip list

      - name: Run tests
        env:
          PYTHONPATH: main
        run: |
          pytest -q --disable-warnings
